### ISSUE TITLE
google auth invalid credentials

### ISSUE THREAD

**Issue by gchadaram** [sreetejadusi/autosmith#1]
displaying error while logging in

**Comment by sreetejadusi** [comment]
The authentication requires Firebase project to be configured, as we are in pilot testing, how about we bypass login and navigate to HomeScreen directly?

**Comment by ghost** [comment]
Yes, we can do that for now.

**Comment by gchadaram** [comment]
looks good to me.

**Comment by Satwikvarma02** [comment]
Fine, let's do that

**Comment by sreetejadusi** [comment]
This pull request closes the issue.
